config/routes.rb
Rails.application.routes.draw do
  root to: 'events#index'
  # post '/events', to: 'events#create'

  resources :events, only: [:index, :show, :create, :update, :destroy]
  resources :chats

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_banner.html.erb
<div class="banner">
  <div class="banner-content">
    <h1>Icebreaker </h1>
    <p>Your new friends are waiting for you</p>
    <!-- <img class="bear" src="http://hddfhm.com/images/polar-bear-clipart-icons-9.png" alt=""> -->
    <%= image_tag "polar_bear_white.svg", class: "bear" %>
    <br>
    <br>

    <%= link_to events_path(@event), class: "hide", id:"btn-hidden", method: :post do %>
    <!-- <span class="margin-top">create event</span> -->
    <% end %>

    <a href="#" class="particle" id="orangebtn">create event</a>

    <br>
    <br>
    <br>
    <br>
    <br>

    <br>
  </div>
  <div class="title">

     <% if @events.count == 1 %>
     <h4 class="events_nearby text-center"> <a href="#" id="scroll"> <%= "#{@events.count} event near you" %> </a> </h4>

     <% elsif @events.count > 0 %>
     <h4 class="events_nearby text-center">
      <a href="#" id="scroll"> <%= "#{@events.count} events near you" %> </a> </h4>

      <% else %>
      <h4 class="events_nearby text-center">no events near you</h4>
      <% end %>
    </div>
</div>
<section id="section07" class="demo scroll2">
  <a href="#">
    <span></span>
    <span></span>
    <span></span>
  </a>
</section>

app/views/shared/_button.html.erb
<button class="action"><svg class="icon icon--rewind"><use xlink:href="#icon-rewind"></use></svg></button>
<button class="particles-button">Register</button>

<script src='js/anime.min.js'></script>
<script src='js/particles.js'></script>
<script src='js/demo.js'></script>

app/views/shared/_card_index.html.erb
<% @events.each do |event| %>
<% if event.status? %>
<div class="card-white">
  <div class="card" style="background-image: /*linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),*/ url(
  <%= event.photo_url %>);"><%= link_to "", event, class: "card-link" %>
  </div>
  <div class="card-category-index"><strong><%= event.name.upcase.truncate(36) %></strong>
    <br>
    <%= event.place_name %>
  </div>
  <div class="card-description-index"><%= event.time.strftime('%d-%h | %Hh%Mm') %> | <%= event.users.count %><i class="fas fa-users"></i><% unless current_user.nil? %> | <a href="https://www.google.com/maps/dir/?api=1&origin=<%= current_user.address %>&destination=<%= event.address %>" target="_blank"><i class="fas fa-map-marker-alt"></i></a><% end %></div>
</div>
<br>
<% end %>
<% end %>

app/views/shared/_card_show.html.erb
<!-- front content -->
<div class="card-white">
  <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= @event.photo_url %>);">
    <% if event.users.count > 2 %>
    <p class="confirmation">Event confirmed</p>
    <% end %>
    </div>
  <div class="card-category"><%= event.place_name %></div>
  <div class="card-description">
    <%= event.time.strftime('%d-%h | %Hh%Mm') %> | <%= event.users.count %>  <i class="fas fa-users"></i>
  </div>
  <div class="card-update"><i class="far fa-edit" id="myCard"></i></div>
  <div class="card-gmaps"><a href="https://www.google.com/maps/dir/?api=1&origin=<%= current_user.address %>&destination=<%= event.address %>" target="_blank"><i class="fas fa-map-marker-alt"></i></a></div>
</div>

app/views/shared/_chat.html.erb
 <div class="container-fluid">
   <div class="row" id="row_box">
     <div class="col-12 chat-text-input" id="<%= @current_user.first_name %>">
     </div>
     <div class="col-12 full-height">
       <div class="container-fluid">
         <div class="chat-box py-2 chat-bg" id="<%= @event.id %>">
          <h4 class="username d-none mb-3"></h4>
          <% @chats.each do |chat| %>
          <% if chat.username == current_user.first_name %>
             <%= render "shared/chat_me", chat: chat %>
             <% else %>
             <%= render "shared/chat_you", chat: chat %>
           <% end %>
           <% end %>
         </div>
       <%= form_with(model: @chat, remote: true, format: :json, id: 'chat-form') do |form| %>
       <div class="field position-relative">
         <%= form.text_field :message, id: :message, class: "form-control margin", required: true, placeholder: "discuss event details" %>
         <%= form.hidden_field :username, value: current_user.first_name %>
         <%= form.hidden_field :event_id, value: @event.id %>
         <%= form.submit "Send", :class => "btn btn-warning" %>
       </div>
       <% end %>
       </div>
     </div>
   </div>
 </div>
</div>

app/views/shared/_chat_me.html.erb
<div class="chat-me">
 <div class="chat-bubble" id="bubble">
   <p class="m-0 chat-message"><%= chat.message %></p>
 </div>
</div>

app/views/shared/_chat_you.html.erb
<% penguins = ["babyblue", "blue", "ginger", "green", "orange", "pink", "purple", "violet", "yellow"] %>
<div class="chat-you" id="chat-all2">
 <div class="chat-bubble2" id="bubble2">
   <span class="chat-user"><strong><%= chat.username %></strong></span>
   <br>
   <span class="chat-message2"><%= chat.message %></span>
 </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_head.html.erb
<%# Apple tags %>
<%= tag.meta(name: 'apple-mobile-web-app-status-bar-style', content: 'black-translucent') %>
<%= tag.meta(name: 'apple-mobile-web-app-capable', content: 'yes') %>
<%= tag.meta(name: 'apple-mobile-web-app-title', content: 'ICEbreaker') %>
<%# Icons %>
<%= tag.link(rel: 'manifest', href: asset_path('manifest.json')) %>
<%= tag.link(rel: 'apple-touch-icon', href: asset_path('icons/frizzbird-96x96.png')) %>
<%= tag.link(rel: 'apple-touch-icon', sizes: '152x152', href: asset_path('icons/frizzbird-152x152.png')) %>
<%= tag.link(rel: 'apple-touch-icon', sizes: '180x180', href: asset_path('icons/frizzbird-180x180.png')) %>
<%= tag.link(rel: 'apple-touch-icon', sizes: '192x192', href: asset_path('icons/frizzbird-192x192.png')) %>
<%# Splashes %>
<%= tag.link(rel: "apple-touch-startup-image", href: asset_path('splashes/splash-1x-768x1024.png' ), media: "(device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 1) and (orientation: portrait)") %>
<%= tag.link(rel: "apple-touch-startup-image", href: asset_path('splashes/splash-2x-640x1136.png' ), media: "(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)") %>
<%= tag.link(rel: "apple-touch-startup-image", href: asset_path('splashes/splash-2x-750x1334.png' ), media: "(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)") %>
<%= tag.link(rel: "apple-touch-startup-image", href: asset_path('splashes/splash-2x-1536x2008.png'), media: "(min-device-width: 768px) and (max-device-width: 1004px) and (-webkit-min-device-pixel-ratio: 2) and (orientation: portrait)") %>
<%= tag.link(rel: "apple-touch-startup-image", href: asset_path('splashes/splash-2x-1536x2048.png'), media: "(min-device-width: 768px) and (max-device-width: 1024px) and (-webkit-min-device-pixel-ratio: 2) and (orientation: portrait)") %>
<%= tag.link(rel: "apple-touch-startup-image", href: asset_path('splashes/splash-3x-1242x2208.png'), media: "(device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)") %>
<%= tag.link(rel: "apple-touch-startup-image", href: asset_path('splashes/splash-3x-1125x2436.png'), media: "(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)") %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <% igloo = image_tag 'igloo.png', class: "home-btn" %>
   <%= link_to igloo, root_path, class: "home-btn" %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right">
    <div class="navbar-wagon-item hidden-md hidden-lg">
      <div class="dropdown">
        <i class="fa fa-bars" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <% if user_signed_in? %>
          <!-- Links when logged in -->
          <li><%= link_to "Profile", edit_user_registration_path, class: "navbar-wagon-item navbar-wagon-link drop-links" %></li>
          <li><%= link_to "Sign out", destroy_user_session_path, class: "navbar-wagon-item navbar-wagon-link drop-links", method: :delete %></li>
          <% else %>
          <!-- Login link (when logged out) -->
          <li><%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link drop-links" %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>